name: publish to nuget
on:
  push:
    branches: [ "refactor/v3" ]
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
          
      - name: Build solution and generate NuGet package
        run: |
          cd UEScript.CLI
          dotnet pack -c Release -o ./nuget  

      # Publish
      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./UEScript.CLI/nuget/*.nupkg --skip-duplicate --no-symbols true